config/routes.rb
Tuiter::Application.routes.draw do
  resources :usuarios do
    member do
	  get :siguiendo, :seguidores
	end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :tuits, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]
  
  root to: 'paginas_estaticas#inicio' #por defecto -> get "paginas_estaticas/inicio"
  match '/ayuda',    to: 'paginas_estaticas#ayuda'
  match '/nosotros', to: 'paginas_estaticas#nosotros'
  match '/contacto', to: 'paginas_estaticas#contacto'
  match '/registro', to: 'usuarios#new'
  match '/ingreso',  to: 'sesiones#new'
  match '/salir',    to: 'sesiones#destroy', via: :delete

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(object.errors.count, "errore") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_estadis.erb
<% @usuario ||= current_user %>
<div class="estadisticas">
  <a href="<%= siguiendo_usuario_path(@usuario) %>">
    <strong id="siguiendo" class="estadisticas">
      <%= @usuario.usuarios_seguidos.count %>
    </strong>
    siguiendo
  </a>
  <a href="<%= seguidores_usuario_path(@usuario) %>">
    <strong id="seguidores" class="estadisticas">
      <%= @usuario.usuarios_seguidores.count %>
    </strong>
    seguidores
  </a>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="tuits">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.usuario), feed_item.usuario %>
  <span class="usuario">
    <%= link_to feed_item.usuario.nombre, feed_item.usuario %>
  </span>
  <span class="content"><%= feed_item.contenido %></span>
  <span class="timestamp">
    Tuitiado hace <%= time_ago_in_words(feed_item.created_at) %> atras.
  </span>
  <% if current_user?(feed_item.usuario) %>
    <%= link_to "eliminar", feed_item, method:  :delete, confirm: "Estas seguro?", title:   feed_item.contenido %>
  <% end %>
</li>

app/views/shared/_tuit_form.html.erb
<%= form_for(@tuit) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :contenido, placeholder: "Compone un nuevo tuit..." %>
  </div>
  <%= f.submit "Tuitear", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= usuario_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.nombre %>
</h1>
<span>
  <%= link_to "ver mi perfil", current_user %>
</span>
<span>
  <%= pluralize(current_user.tuits.count, "tuit") %>
</span>

app/views/shared/_user_info.html.erb.erb
<a href="<%= usuario_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.nombre %>
</h1>
<span>
  <%= link_to "ver mi perfil", current_user %>
</span>
<span>
  <%= pluralize(current_user.tuits.count, "tuit") %>
</span>