config/routes.rb
Tuiter::Application.routes.draw do
  resources :usuarios do
    member do
	  get :siguiendo, :seguidores
	end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :tuits, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]
  
  root to: 'paginas_estaticas#inicio' #por defecto -> get "paginas_estaticas/inicio"
  match '/ayuda',    to: 'paginas_estaticas#ayuda'
  match '/nosotros', to: 'paginas_estaticas#nosotros'
  match '/contacto', to: 'paginas_estaticas#contacto'
  match '/registro', to: 'usuarios#new'
  match '/ingreso',  to: 'sesiones#new'
  match '/salir',    to: 'sesiones#destroy', via: :delete

end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController

  def new
  end

  def create
    @usuario = Usuario.find_by_email(params[:sesion][:email])
    if @usuario && @usuario.authenticate(params[:sesion][:password])
      sign_in @usuario
      redirect_back_or @usuario
    else
      flash.now[:error] = 'Combinacion email/contrasena invalida!'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/helpers/sesiones_helper.rb
module SesionesHelper

  def sign_in(usuario)
    cookies.permanent[:remember_token] = usuario.remember_token
    current_user = usuario
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(usuario)
    @current_user = usuario
  end
  
  def current_user
    @current_user ||= Usuario.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(usuario)
    usuario == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to ingreso_path, notice: "Por favor inicia sesion."
    end
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
end

app/views/sesiones/new.html.erb
<% provide(:title, "Ingreso") %>
<h1>Inicia Sesion</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(:sesion, url: sesiones_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "Contrasena" %>
      <%= f.password_field :password %>

      <%= f.submit "Ingresa", class: "btn btn-large btn-primary" %>
    <% end %>

    <p>Usuario nuevo? <%= link_to "Registrate ahora!", registro_path %></p>
  </div>
</div>