config/routes.rb
Tuiter::Application.routes.draw do
  resources :usuarios do
    member do
	  get :siguiendo, :seguidores
	end
  end
  resources :sesiones, only: [:new, :create, :destroy]
  resources :tuits, only: [:create, :destroy]
  resources :relacions, only: [:create, :destroy]
  
  root to: 'paginas_estaticas#inicio' #por defecto -> get "paginas_estaticas/inicio"
  match '/ayuda',    to: 'paginas_estaticas#ayuda'
  match '/nosotros', to: 'paginas_estaticas#nosotros'
  match '/contacto', to: 'paginas_estaticas#contacto'
  match '/registro', to: 'usuarios#new'
  match '/ingreso',  to: 'sesiones#new'
  match '/salir',    to: 'sesiones#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>{~.~} <a href="http://twitter.com/#!/daswort" target="_blank"> daswort</a></small>
  <nav>
    <ul>
      <li><%= link_to "Nosotros", nosotros_path %></li>
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><a href="http://lun.cl" target="_blank">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "tuiter", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Inicio", root_path %></li>
              <li><%= link_to "Ayuda", ayuda_path %></li>
			  <% if signed_in? %>
			    <li><%= link_to "Usuarios", usuarios_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Cuenta <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Perfil", current_user %></li>
                    <li><%= link_to "Configuracion", edit_usuario_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Cerrar Sesion", salir_path, method: "delete" %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Iniciar Sesion", ingreso_path %></li>
			  <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_usuario.html.erb
<li>
  <%= gravatar_for usuario %>
  <%= link_to usuario.nombre, usuario %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
	  <%= render 'layouts/footer' %>
    </div>
  </body>
</html>